import re


def clean_transcript(text: str) -> str:
    """Normalize transcript text without changing meeting meaning."""
    if not text:
        return ""

    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = text.replace("\ufeff", "")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r" *\n *", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)

    artifact_patterns = [
        r"(?im)^\s*(transcript generated by|recording started|recording stopped).*$",
        r"(?im)^\s*(automated transcript|live transcript)\s*$",
        r"(?im)^\s*\[?(inaudible|crosstalk|silence)\]?\s*$",
    ]
    for pattern in artifact_patterns:
        text = re.sub(pattern, "", text)

    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip() + ("\n" if text.strip() else "")

